import {makeFlow,scenarioInfo,tokenInfo,stations,guideHTML,sourcesHTML,audits,refs} from './content.mjs';
import {ParkScene} from './scene.mjs';
const $=id=>document.getElementById(id);
const state={kind:'oidc',scenario:'happy',time:0,playing:false,speed:1,labels:true};
let flow=makeFlow(state.kind),lastFrame=0,lastKey='',renderTime=0,modalWasPlaying=false;
const checked=new Set();
const scene=new ParkScene($('park'),$('stationLabels'),openStation);
const duration=6500;
const failure=()=>scenarioInfo[state.scenario]?.index;
const limit=()=>failure()===undefined?flow.length-.001:failure()+.86;
const index=()=>Math.min(flow.length-1,Math.floor(state.time));
const blocked=()=>failure()!==undefined&&state.time>=limit()-.001;
const finished=()=>state.time>=limit()-.001;
function currentStep(){const s=flow[index()];if(index()===failure()){const err=scenarioInfo[state.scenario];return {...s,title:err.title,description:err.description,why:err.why,wire:err.wire,source:err.source,path:err.path??s.path,...(state.scenario==='denied'?{from:'provider',to:'client',channel:'Через браузер'}:{})};}return s;}
function updateTimeline(){const n=index();$('timeline').value=String(Math.round(state.time*100));$('timeline').setAttribute('aria-valuetext',`Шаг ${n+1} из ${flow.length}: ${currentStep().title}`);}
function sync(force=false){const n=index(),bad=blocked();const key=[state.kind,state.scenario,n,state.playing,bad,finished()].join(':');if(force||key!==lastKey){lastKey=key;const s=currentStep();$('stepBadge').textContent='ШАГ '+String(n+1).padStart(2,'0');$('stepType').textContent=bad?'ОСТАНОВКА':s.channel.toUpperCase();$('stepTitle').textContent=s.title;$('stepDescription').textContent=s.description;$('takeaway').textContent=s.why;$('wireCode').textContent=s.wire;$('stepSource').href=s.source;const stationName=id=>id==='api'?(state.kind==='oidc'?'UserInfo':'API'):stations[id].name;const route=s.path??[s.from,s.to];$('route').textContent=s.from===s.to&&!s.path?stationName(s.from)+' · локально':route.map(stationName).join(' → ');$('stepCount').textContent=String(n+1).padStart(2,'0')+' / '+String(flow.length).padStart(2,'0');$('channelLabel').textContent=s.channel;$('playIcon').textContent=state.playing?'Ⅱ':finished()?'↺':'▶';$('playLabel').textContent=state.playing?'Пауза':finished()?'Повторить':state.time===0?'Запустить':'Продолжить';$('statusText').textContent=bad?'Остановлено проверкой':finished()?'Маршрут завершён':state.playing?'Обмен в движении':state.time===0?'Готов к отправлению':'На паузе';$('signal').className='signal'+(bad?' error':state.playing?' playing':'');$('prev').disabled=n===0;$('next').disabled=n>=flow.length-1||n===failure();$('scenarioHint').textContent=bad?'Защита сработала. Дальнейший обмен заблокирован.':state.scenario==='happy'?'Выберите сбой: поезд остановится на защитной проверке.':'Сценарий выбран. Остановка на шаге '+(failure()+1)+'.';$('scenario').closest('.scenario-control').classList.toggle('failed',bad);const earned=(n===failure()&&['expired','nonce'].includes(state.scenario)?flow[n].bag:s.bag)||[];document.querySelectorAll('.token').forEach(el=>{const has=earned.includes(el.dataset.token);el.classList.toggle('available',has);el.classList.toggle('inactive',!has);el.title=has?'На этом этапе у клиента':'Объяснение токена (ещё не получен или уже погашен)';});document.querySelectorAll('.step-btn').forEach((el,i)=>{el.classList.toggle('active',i===n);el.classList.toggle('done',i<n);el.classList.toggle('failed',i===n&&bad);el.setAttribute('aria-current',i===n?'step':'false');el.disabled=failure()!==undefined&&i>failure();});}updateTimeline();scene.draw({step:currentStep(),progress:Math.min(1,Math.max(0,(state.time-index()-.08)/.82)),failed:bad,kind:state.kind});}
function setTime(t){state.time=Math.max(0,Math.min(limit(),t));state.playing=false;sync(true);}
function togglePlay(){if($('detailDialog').open)return;if(finished())state.time=0;state.playing=!state.playing;lastFrame=performance.now();sync(true);}
function setupFlow(){flow=makeFlow(state.kind);state.time=0;state.playing=false;$('timeline').max=String(Math.ceil((flow.length-.001)*100));$('steps').replaceChildren();flow.forEach((s,i)=>{const button=document.createElement('button');button.className='step-btn';button.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span><span>'+s.short+'</span>';button.setAttribute('aria-label','Шаг '+(i+1)+': '+s.title);button.addEventListener('click',()=>setTime(i));$('steps').append(button);});$('flowCaption').textContent=({oidc:'Серверное приложение · Authorization Code + PKCE',oauth:'Делегированный доступ · без OpenID Connect',refresh:'Предполагается ранее выданный refresh token',m2m:'Confidential client · без пользователя'})[state.kind];document.querySelector('.model-badge').textContent=state.kind==='m2m'?'CLIENT CREDENTIALS':state.kind==='refresh'?'REFRESH TOKEN':'CODE + PKCE';document.querySelector('.scene-heading h1').textContent=({oidc:'Вход — это целое путешествие.',oauth:'Разрешение на доступ. По шагам.',refresh:'Новый пропуск, та же поездка.',m2m:'Когда сервису нужен другой сервис.'})[state.kind];document.querySelector('.scene-heading p').textContent=({oidc:'Проследите путь от первого клика до подтверждённой личности.',oauth:'Как приложение получает ограниченный доступ к чужому API.',refresh:'Что происходит после истечения access token.',m2m:'OAuth без браузера, пользовательского входа и ID Token.'})[state.kind];document.querySelector('.scene-caption').textContent=state.kind==='oidc'?'Одна поездка · один вход':state.kind==='m2m'?'Сервис → сервис':'Одна поездка · один обмен';const labels=document.querySelectorAll('.timeline-labels span');labels[1].textContent=state.kind==='refresh'?'Ротация':'Получение токенов';labels[2].textContent=state.kind==='oidc'?'Сессия':'Результат';for(const option of $('scenario').options){option.disabled=option.value!=='happy'&&(['refresh','m2m'].includes(state.kind)||(state.kind==='oauth'&&option.value==='nonce'));}if($('scenario').selectedOptions[0].disabled){state.scenario='happy';$('scenario').value='happy';}$('scenario').disabled=['refresh','m2m'].includes(state.kind);sync(true);}
for(const[id,t]of Object.entries(tokenInfo)){const btn=document.createElement('button');btn.className='token inactive';btn.dataset.token=id;btn.style.setProperty('--token',t.color);btn.innerHTML='<i></i>'+t.name;btn.addEventListener('click',()=>openToken(id));$('tokenButtons').append(btn);}
$('play').addEventListener('click',togglePlay);$('reset').addEventListener('click',()=>setTime(0));$('prev').addEventListener('click',()=>setTime(index()-1));$('next').addEventListener('click',()=>setTime(index()+1));$('timeline').addEventListener('input',e=>setTime(Number(e.target.value)/100));$('speed').addEventListener('change',e=>{state.speed=Number(e.target.value);});$('flow').addEventListener('change',e=>{state.kind=e.target.value;setupFlow();});$('scenario').addEventListener('change',e=>{state.scenario=e.target.value;setTime(0);});$('zoomIn').addEventListener('click',()=>{scene.setZoom(scene.zoom+.15);sync();});$('zoomOut').addEventListener('click',()=>{scene.setZoom(scene.zoom-.15);sync();});$('cameraReset').addEventListener('click',()=>{scene.setZoom(1);sync();});$('labelsToggle').addEventListener('click',()=>{state.labels=!state.labels;$('stationLabels').hidden=!state.labels;$('labelsToggle').setAttribute('aria-pressed',String(state.labels));});
document.addEventListener('keydown',e=>{if($('detailDialog').open||e.ctrlKey||e.altKey||e.metaKey)return;if(/INPUT|SELECT|TEXTAREA|BUTTON|A/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay();}if(e.code==='ArrowRight'){e.preventDefault();setTime(index()+1);}if(e.code==='ArrowLeft'){e.preventDefault();setTime(index()-1);}if(e.code==='KeyR')setTime(0);});
document.addEventListener('visibilitychange',()=>{if(document.hidden){state.playing=false;sync(true);}});
function frame(now){const dt=lastFrame?Math.max(0,Math.min(100,now-lastFrame)):0;lastFrame=now;if(state.playing){state.time=Math.min(limit(),state.time+dt/duration*state.speed);if(finished())state.playing=false;}if(now-renderTime>32||state.playing){sync();renderTime=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function openDialog(html,eyebrow='СПРАВОЧНИК'){modalWasPlaying=state.playing;state.playing=false;sync(true);$('dialogContent').innerHTML=html;$('dialogEyebrow').textContent=eyebrow;$('detailDialog').showModal();$('detailDialog').scrollTop=0;}
$('closeDialog').addEventListener('click',()=>$('detailDialog').close());$('detailDialog').addEventListener('click',e=>{if(e.target===$('detailDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});$('detailDialog').addEventListener('close',()=>{modalWasPlaying=false;sync(true);});
$('guideOpen').addEventListener('click',()=>openDialog(guideHTML));$('sourcesOpen').addEventListener('click',()=>openDialog(sourcesHTML,'СПЕЦИФИКАЦИИ'));
function openToken(id){const t=tokenInfo[id];openDialog('<h2>'+t.title+'</h2><span class="token-place">'+t.where+'</span><p>'+t.text+'</p><pre>'+esc(t.example)+'</pre><p><a href="'+t.source+'" target="_blank" rel="noopener noreferrer">Спецификация ↗</a></p>','БАГАЖ ЗАПРОСА');}
function openStation(id){const s=stations[id],texts={browser:'Браузер переносит front-channel запросы и ответы через перенаправления. Он не является confidential client. В этой модели в нём хранится cookie приложения; токены и секрет клиента остаются на сервере.',client:'Ваше серверное приложение играет роль OAuth client и, при использовании OIDC, Relying Party. Оно инициирует обмен, аутентифицируется на token endpoint, проверяет ID Token и создаёт собственную сессию.',provider:'Провайдер объединяет роли Authorization Server и OpenID Provider. Он аутентифицирует пользователя, обрабатывает авторизацию, выпускает код и токены. Authorization endpoint посещает браузер; token endpoint вызывает клиент.',api:state.kind==='oidc'?'В этом маршруте станция представляет UserInfo endpoint самого OpenID Provider. Она принимает access token и возвращает claims. Её sub должен совпадать с sub проверенного ID Token.':'Защищённый API / Resource Server принимает access token, проверяет его действительность, целевой ресурс и scope. ID Token не служит пропуском к этому API.'};openDialog('<h2>'+(id==='api'?(state.kind==='oidc'?'UserInfo':'API ресурсов'):s.name)+'</h2><span class="token-place">'+(id==='api'&&state.kind!=='oidc'?'Resource Server':s.role)+'</span><p>'+texts[id]+'</p>','УЧАСТНИК ПРОТОКОЛА');}
$('auditOpen').addEventListener('click',()=>{openDialog('<h2>Перед обновлением реализации</h2><p>Рабочая карта ревью, не подтверждение соответствия. Код вашего проекта ещё не проверялся. Отметки сохраняются до перезагрузки страницы.</p><p class="audit-progress" id="auditProgress"></p>'+audits.map(([title,desc],i)=>'<label class="audit-item"><input type="checkbox" data-audit="'+i+'" '+(checked.has(i)?'checked':'')+'><span><b>'+title+'</b><small>'+desc+'</small></span></label>').join('')+'<p style="margin-top:20px"><a href="'+refs.bcp+'" target="_blank" rel="noopener noreferrer">RFC 9700 ↗</a> · <a href="'+refs.core+'" target="_blank" rel="noopener noreferrer">OIDC Core ↗</a></p>','КАРТА МИГРАЦИИ');const update=()=>$('auditProgress').textContent=checked.size+' / '+audits.length+' пунктов проверено';document.querySelectorAll('[data-audit]').forEach(el=>el.addEventListener('change',()=>{el.checked?checked.add(Number(el.dataset.audit)):checked.delete(Number(el.dataset.audit));update();}));update();});
setupFlow();
// Progressive enhancement: an agent controls the same simulation as the visitor.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_oauth_simulation',title:'Настроить симуляцию OAuth',description:'Select a displayed flow or scenario, pause/play, and navigate to a step of this educational simulation. Does not authenticate or make HTTP requests.',inputSchema:{type:'object',properties:{flow:{type:'string',enum:['oidc','oauth','refresh','m2m']},scenario:{type:'string',enum:Object.keys(scenarioInfo)},step:{type:'integer',minimum:1},playing:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected an object');for(const key of Object.keys(input))if(!['flow','scenario','step','playing'].includes(key))throw Error('Unknown input field');const kind=input.flow??state.kind,scenario=input.scenario??state.scenario;if(!['oidc','oauth','refresh','m2m'].includes(kind)||!Object.hasOwn(scenarioInfo,scenario))throw Error('Unknown flow or scenario');if((['refresh','m2m'].includes(kind)&&scenario!=='happy')||(kind==='oauth'&&scenario==='nonce'))throw Error('Scenario unavailable for this flow');const total=makeFlow(kind).length,max=scenario==='happy'?total:scenarioInfo[scenario].index+1;if(input.step!==undefined&&(!Number.isInteger(input.step)||input.step<1||input.step>max))throw Error('Step outside available route');if(input.playing!==undefined&&typeof input.playing!=='boolean')throw Error('playing must be boolean');if($('detailDialog').open)throw Error('Close the reference dialog first');state.kind=kind;state.scenario=scenario;$('flow').value=kind;$('scenario').value=scenario;setupFlow();if(input.step!==undefined)setTime(input.step-1);state.playing=input.playing??false;sync(true);return {flow:state.kind,scenario:state.scenario,step:index()+1,playing:state.playing,title:currentStep().title};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
