import {makeProjectFlow,isProject} from './project.mjs';
export const refs={core:'https://openid.net/specs/openid-connect-core-1_0.html',oauth:'https://www.rfc-editor.org/rfc/rfc6749.html',pkce:'https://www.rfc-editor.org/rfc/rfc7636.html',bcp:'https://www.rfc-editor.org/rfc/rfc9700.html',discovery:'https://openid.net/specs/openid-connect-discovery-1_0.html',bearer:'https://www.rfc-editor.org/rfc/rfc6750.html',introspection:'https://www.rfc-editor.org/rfc/rfc7662.html',jwt:'https://www.rfc-editor.org/rfc/rfc9068.html',revoke:'https://www.rfc-editor.org/rfc/rfc7009.html',logout:'https://openid.net/specs/openid-connect-rpinitiated-1_0.html'};
export const stations={browser:{name:'Браузер',role:'Пользователь / user agent',color:'#f9b668',x:-7,z:5,h:3.3},client:{name:'Приложение',role:'Client / Relying Party',color:'#69c7e3',x:5,z:5,h:3.6},provider:{name:'Провайдер',role:'Authorization Server / OP',color:'#d6adf7',x:-5,z:-5,h:5.2},api:{name:'Resource Server',role:'Бизнес-API · access token',color:'#b4ef65',x:7,z:-5,h:3.5}};
const step=(title,short,from,to,channel,description,why,wire,source,bag=[],path)=>({title,short,from,to,channel,description,why,wire,source,bag,path});
const verifier='dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk';
const challenge='E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM';
export function makeFlow(kind){if(isProject(kind))return makeProjectFlow(kind,refs);const oidc=kind==='oidc';
if(kind==='refresh')return [
step('Срок доступа истёк','Истечение','api','client','Сервер → сервер','API отклоняет просроченный access token. Сессия приложения при этом может ещё существовать.','Короткая жизнь access token ограничивает окно его использования. Refresh token был получен в предыдущем разрешённом обмене.','HTTP/1.1 401 Unauthorized\nWWW-Authenticate: Bearer\n  error="invalid_token"',refs.bearer+'#section-3.1',['refresh']),
step('Запрос нового доступа','Refresh-запрос','client','provider','Сервер → сервер','Приложение отправляет refresh token провайдеру и аутентифицируется как клиент. Браузер в этом обмене не участвует.','Нельзя расширить разрешения по сравнению с исходным grant. Выдача refresh token зависит от политики сервера.','POST /token\nAuthorization: Basic <client credentials>\nContent-Type: application/x-www-form-urlencoded\n\ngrant_type=refresh_token\n&refresh_token=rt_demo_01',refs.oauth+'#section-6',['refresh']),
step('Ротация refresh token','Ротация','provider','client','Сервер → сервер','В этом примере провайдер выдаёт новый access token и заменяет refresh token. Старый refresh token больше не принимается.','Для public clients RFC 9700 требует ротацию или привязку refresh token к отправителю; для остальных политика определяется профилем.','HTTP/1.1 200 OK\nCache-Control: no-store\n{\n  "access_token": "at_demo_02",\n  "token_type": "Bearer",\n  "expires_in": 300,\n  "refresh_token": "rt_demo_02"\n}',refs.bcp+'#section-4.14',['access','refresh']),
step('Повторный запрос к API','Новый запрос','client','api','Сервер → сервер','Приложение использует новый access token. Refresh token остаётся в хранилище клиента.','Ротация refresh token не означает мгновенный отзыв всех ранее выданных access tokens.','GET /documents\nHost: api.example\nAuthorization: Bearer at_demo_02',refs.bearer+'#section-2.1',['access','refresh']),
step('Доступ восстановлен','Результат','api','client','Сервер → сервер','API проверил актуальность токена, целевой ресурс и разрешение documents:read. Запрос завершён.','Если refresh token истёк, отозван или повторно использован после ротации, обмен завершается ошибкой; может потребоваться новый вход.','HTTP/1.1 200 OK\n{ "documents": [{"id": "doc_demo"}] }',refs.oauth+'#section-5.2',['access','refresh'])];
if(kind==='m2m')return [
step('У сервиса своя роль','Сервис','client','client','Локально','Серверное приложение обращается к API от собственного имени. Пользователя и его входа в этом grant нет.','Client credentials предназначен для confidential clients, способных хранить ключ или секрет.','client_id = maintenance-service\nscope = documents:read\n# Нет user session, nonce или ID Token',refs.oauth+'#section-4.4'),
step('Аутентификация сервиса','Token-запрос','client','provider','Сервер → сервер','Сервис запрашивает access token, аутентифицируясь разрешённым для него методом.','Секрет или закрытый ключ остаётся на сервере. client_id сам по себе не доказывает подлинность клиента.','POST /token\nAuthorization: Basic <client credentials>\nContent-Type: application/x-www-form-urlencoded\n\ngrant_type=client_credentials\n&scope=documents%3Aread',refs.oauth+'#section-4.4.2'),
step('Токен для сервиса','Access token','provider','client','Сервер → сервер','Провайдер выдаёт access token с полномочиями сервиса. ID Token не появляется.','Refresh token для client credentials по RFC 6749 выдавать не следует: сервис может повторно аутентифицироваться.','HTTP/1.1 200 OK\nCache-Control: no-store\n{ "access_token": "at_service",\n  "token_type": "Bearer",\n  "expires_in": 300,\n  "scope": "documents:read" }',refs.oauth+'#section-4.4.3',['access']),
step('Сервис вызывает API','Запрос API','client','api','Сервер → сервер','API проверяет токен и права сервиса, затем обрабатывает запрос.','Не подменяйте service identity личностью человека: это другая модель разрешений.','GET /documents\nHost: api.example\nAuthorization: Bearer at_service',refs.bearer+'#section-2.1',['access']),
step('Машина ответила машине','Результат','api','client','Сервер → сервер','Ответ приходит сервису. Cookies браузера и пользовательская сессия не создаются.','OAuth используется и без OpenID Connect, браузера или человека.','HTTP/1.1 200 OK\n{ "documents": [{"id": "doc_demo"}] }',refs.oauth+'#section-4.4',['access'])];
return [
step('Подготовка поездки','Подготовка','client','client','Локально','Клиент заранее зарегистрирован. Приложение создаёт state, '+(oidc?'nonce и ':'')+'PKCE verifier и связывает их с одной попыткой входа.','Демонстрация использует confidential web client. Секреты и токены хранятся на сервере; браузер получает cookie сессии.','client_id = park-web\nredirect_uri = https://app.example/callback\nstate = st_demo\n'+(oidc?'nonce = n_demo\n':'')+'code_verifier = <random 43–128 chars>\ncode_challenge = BASE64URL(SHA256(verifier))',refs.pkce+'#section-4.1'),
step(oidc?'Пользователь нажимает «Войти»':'Пользователь подключает API','Начало','browser','client','Через браузер',oidc?'Пользователь открывает приложение и запускает вход через провайдера.':'Пользователь разрешает приложению читать список документов из внешнего API.','Пользовательский пароль не нужно отдавать приложению: проверять его будет провайдер.','GET /'+(oidc?'login':'connect')+'\nHost: app.example',refs.oauth+'#section-4.1'),
step('Перенаправление к провайдеру','Authorize','client','provider','Через браузер','Ответ приложения направляет браузер на authorization endpoint. '+(oidc?'scope=openid включает OIDC.':'Здесь нет scope=openid: это запрос делегированного доступа.'),'state связывает ответ с запросом; PKCE связывает будущий code с экземпляром клиента. nonce привязывает ID Token к попытке входа.','HTTP 302 → браузер → GET /authorize\nHost: id.example\nresponse_type=code\n&client_id=park-web\n&redirect_uri=https%3A%2F%2Fapp.example%2Fcallback\n&scope='+(oidc?'openid%20profile':'documents%3Aread')+'\n&state=st_demo\n'+(oidc?'&nonce=n_demo\n':'')+'&code_challenge='+challenge+'\n&code_challenge_method=S256',refs.oauth+'#section-4.1.1',[],['client','browser','provider']),
step('Кто вы и что разрешаете?','Вход и согласие','provider','provider','У провайдера','Провайдер аутентифицирует пользователя и определяет, какие права выдать. Уже существующая SSO-сессия может избавить от повторного ввода пароля.','Конкретные экраны, пароль, MFA и политика согласия не задаются OAuth. Consent не обязательно показывать при каждом входе.','Проверка зарегистрированного redirect_uri\nАутентификация пользователя\nРешение об авторизации\nВыдача короткоживущего одноразового code',refs.oauth+'#section-4.1.2'),
step('Назад с одноразовым кодом','Callback','provider','client','Через браузер','Провайдер возвращает браузер на callback приложения с code и state. Токены пока не выдаются браузеру.','Code — промежуточное одноразовое разрешение. Его нельзя использовать как access token.','HTTP 302 → браузер →\nhttps://app.example/callback\n  ?code=code_demo\n  &state=st_demo',refs.oauth+'#section-4.1.2',['code'],['provider','browser','client']),
step('Тот ли это ответ?','Проверка state','client','client','Проверка','Приложение сравнивает state с сохранённым значением этой попытки и проверяет привязку к браузерной сессии.','В модели включены state, nonce и PKCE одновременно. Они проверяют разные связи; правила защиты от CSRF зависят от выбранного профиля.','received_state === saved_state\nsaved_state belongs to this browser session\ntransaction has not been consumed',refs.bcp+'#section-4.7',['code']),
step('Обмен кода на токены','Token-запрос','client','provider','Сервер → сервер','Приложение отправляет code, тот же redirect_uri и исходный verifier напрямую в token endpoint. Здесь оно также аутентифицируется как клиент.','Провайдер проверяет код, срок, одноразовость, client_id, redirect_uri и соответствие verifier исходному challenge.','POST /token\nAuthorization: Basic <client credentials>\nContent-Type: application/x-www-form-urlencoded\n\ngrant_type=authorization_code\n&code=code_demo\n&redirect_uri=https%3A%2F%2Fapp.example%2Fcallback\n&code_verifier='+verifier,refs.pkce+'#section-4.6',['code']),
step(oidc?'Два токена — две задачи':'Разрешение получено','Выдача токенов','provider','client','Сервер → сервер',oidc?'Провайдер возвращает ID Token для клиента и access token для UserInfo. Одноразовый code погашен.':'Провайдер возвращает access token для API. Без OIDC ID Token не выдаётся.','Refresh token необязателен и зависит от политики. В этом входе он не запрашивается; его жизнь показана отдельным маршрутом.','HTTP/1.1 200 OK\nCache-Control: no-store\n{\n  "access_token": "at_demo",\n  "token_type": "Bearer",\n  "expires_in": 300'+(oidc?',\n  "id_token": "<signed JWT>"':'')+'\n}',oidc?refs.core+'#TokenResponse':refs.oauth+'#section-5.1',oidc?['id','access']:['access']),
step(oidc?'Проверить, прежде чем доверять':'Сохранить разрешение','Проверка токенов','client','client','Проверка',oidc?'Приложение проверяет ID Token: доверенный issuer, подпись, audience, срок и nonce. При нескольких aud проверяется azp согласно профилю.':'Клиент сохраняет access token и его срок. Он не должен выводить личность пользователя из произвольного access token.','JWT можно декодировать без ключа. Декодирование не означает проверку подписи и не устанавливает доверие.',oidc?'verify_signature(allowed_alg, trusted_JWKS)\niss === "https://id.example"\naud includes "park-web"\nexp > now; check iat policy\nnonce === saved_nonce\ncheck azp when applicable\nuser_key = (iss, sub)':'store_on_server(access_token, expires_in)\n# Формат access token задаёт провайдер\n# JWT и opaque tokens допустимы',oidc?refs.core+'#IDTokenValidation':refs.oauth+'#section-1.4',oidc?['id','access']:['access']),
step(oidc?'Запрос профиля':'Запрос документов',oidc?'UserInfo':'Вызов API','client',oidc?'provider':'api','Сервер → сервер',oidc?'Клиент отправляет access token в UserInfo endpoint провайдера. Это endpoint провайдера, а не отдельный бизнес-сервис справа на карте.':'Клиент передаёт access token в целевой API, для которого выдано разрешение documents:read.','Access token не является универсальным пропуском: получатель и выданные права должны подходить запрошенному ресурсу.','GET /'+(oidc?'userinfo':'documents')+'\nHost: '+(oidc?'id.example':'api.example')+'\nAuthorization: Bearer at_demo',oidc?refs.core+'#UserInfoRequest':refs.bearer+'#section-2.1',oidc?['id','access']:['access']),
step(oidc?'Профиль того же пользователя':'API применяет разрешения',oidc?'Профиль':'Результат',oidc?'provider':'api','client','Сервер → сервер',oidc?'UserInfo возвращает claims. Клиент обязан сопоставить sub в этом ответе с sub проверенного ID Token.':'API проверяет действительность access token и разрешения; затем возвращает данные.','JWT access token проверяют по согласованному профилю; opaque token можно проверить через защищённый introspection endpoint.',oidc?'HTTP/1.1 200 OK\n{ "sub": "visitor_42", "name": "Алекс" }\n\nuserinfo.sub === id_token.sub':'HTTP/1.1 200 OK\n{ "documents": [{"id": "doc_demo"}] }',oidc?refs.core+'#UserInfoResponse':refs.introspection+'#section-2.2',oidc?['id','access']:['access']),
step(oidc?'Добро пожаловать в приложение':'Подключение готово',oidc?'Сессия':'Готово','client','browser','Через браузер',oidc?'После успешных проверок приложение создаёт собственную сессию. Браузер получает cookie, а токены остаются на сервере.':'Доступ к внешнему API подключён. Сам по себе этот OAuth-обмен не является стандартным доказательством личности для входа.','Сессия приложения, SSO-сессия провайдера и срок токенов — разные механизмы. Они не обязаны заканчиваться одновременно.','HTTP/1.1 302 Found\nLocation: /\nSet-Cookie: __Host-session=<opaque>;\n  Secure; HttpOnly; SameSite=Lax; Path=/\n\n# Пример архитектуры приложения, не требование OIDC',refs.core+'#Overview',oidc?['id','access','session']:['access'])];}
export const scenarioInfo={happy:{name:'Всё корректно'},state:{name:'Подменён state',index:5,title:'Ответ отклонён: state',description:'Полученный state не соответствует сохранённой попытке. Клиент прекращает обработку callback; обмена кода и входа не будет.',why:'state нужно связывать с конкретной сессией и одноразовой транзакцией. Простого наличия параметра недостаточно.',wire:'received_state = "st_foreign"\nsaved_state = "st_demo"\n\nClient: reject callback\nNo token request; no login session',source:refs.bcp+'#section-4.7'},pkce:{name:'Неверный verifier',index:6,title:'Код не открывает ворота',description:'Сервер сравнил S256(verifier) с challenge и отклонил обмен. Владеть одним code недостаточно.',why:'PKCE защищает обмен от перехвата и инъекции кода, но не заменяет аутентификацию confidential client.',wire:'BASE64URL(SHA256(verifier)) != challenge\n\nHTTP/1.1 400 Bad Request\n{ "error": "invalid_grant" }',source:refs.pkce+'#section-4.6'},nonce:{name:'Не совпадает nonce',index:8,title:'ID Token от другой попытки',description:'Подпись может быть корректной, но nonce отличается. Клиент не принимает такой ID Token и не создаёт сессию.',why:'Когда nonce отправлен в запросе, его значение обязано совпасть с nonce в ID Token.',wire:'id_token.nonce = "n_other"\nsaved_nonce = "n_demo"\n\nClient: reject ID Token\nNo authenticated session',source:refs.core+'#IDTokenValidation'},expired:{name:'Истёк access token',index:10,title:'Пропуск больше не действует',description:'Ресурс отклоняет истёкший access token. В этом маршруте refresh token не выдавался: нужен новый authorization flow.',why:'Истечение access token не говорит само по себе, закончилась ли пользовательская сессия у клиента или OP.',wire:'HTTP/1.1 401 Unauthorized\nWWW-Authenticate: Bearer\n  error="invalid_token"',source:refs.bearer+'#section-3.1'},denied:{name:'Пользователь отказал',index:3,title:'Согласие не получено',description:'Провайдер возвращает access_denied через браузер на предварительно проверенный callback. Клиент проверяет state и показывает отказ.',why:'Нельзя редиректить ошибку на незарегистрированный redirect_uri. Ошибка не должна превращаться в успешную сессию.',wire:'HTTP 302 → browser → callback\n?error=access_denied\n&state=st_demo\n\nNo code; no tokens',source:refs.oauth+'#section-4.1.2.1',path:['provider','browser','client']}};
export const tokenInfo={
code:{name:'Code',color:'#f9b668',title:'Authorization code',where:'Браузер → клиент → token endpoint',text:'Короткоживущий одноразовый код для обмена на токены. Привязан к клиенту и redirect_uri, а при PKCE — ещё и к challenge. Сам по себе не предоставляет доступ к API.',example:'code=code_demo\nLifetime: short\nRedeem: once\nBound to client + redirect_uri + PKCE',source:refs.oauth+'#section-4.1.2'},
id:{name:'ID Token',color:'#d6adf7',title:'ID Token — кто вошёл',where:'Провайдер → Relying Party',text:'Подписанный JWT об аутентификации пользователя. aud содержит client_id. Личность связывается с парой (iss, sub), а не с email. Не используйте его как bearer-пропуск к произвольному API.',example:'{\n  "iss": "https://id.example",\n  "sub": "visitor_42",\n  "aud": "park-web",\n  "iat": 1789473600,\n  "exp": 1789473900,\n  "nonce": "n_demo"\n}\n# Иллюстрация payload, не валидный токен',source:refs.core+'#IDToken'},
access:{name:'Access',color:'#69c7e3',title:'Access token — что разрешено',where:'Клиент → целевой Resource Server',text:'Разрешение на доступ к ресурсу. Может быть JWT или непрозрачной строкой. API проверяет его действительность, целевой ресурс и права. Формат и назначение согласуются с провайдером. Bearer-токен может использовать любой, кто им завладел.',example:'Authorization: Bearer at_demo\n\nOIDC route: UserInfo resource\nOAuth route: documents API / documents:read\n# Это разные примеры выдачи токенов',source:refs.bearer+'#section-1.2'},
refresh:{name:'Refresh',color:'#b4ef65',title:'Refresh token — продлить доступ',where:'Клиент → token endpoint',text:'Позволяет запросить новый access token без повторного взаимодействия с пользователем, пока grant действителен. Не передаётся API. Выдача необязательна. Для public clients нужны ротация или привязка к отправителю.',example:'grant_type=refresh_token\nrefresh_token=rt_demo_01\n\nRotation: rt_demo_01 → rt_demo_02\nOld refresh token becomes invalid',source:refs.bcp+'#section-4.14'},
session:{name:'Session',color:'#e4d7b9',title:'Cookie — сессия приложения',where:'Приложение ↔ браузер',text:'В показанной серверной архитектуре cookie содержит непрозрачный идентификатор сессии. Токены лежат на сервере. Это решение приложения: OIDC не задаёт способ хранения его сессии.',example:'Set-Cookie: __Host-session=<opaque>;\nSecure; HttpOnly; SameSite=Lax; Path=/\n\n# CSRF-защита нужна и обычным\n# изменяющим запросам приложения',source:refs.bcp+'#section-4.7'}};
const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
export const guideHTML=`<h2>Один парк, два разных вопроса.</h2><p>OAuth 2.0 описывает, как клиент получает ограниченный доступ к ресурсу. OpenID Connect добавляет поверх OAuth стандартный способ сообщить клиенту, кто аутентифицировался. Здесь «OpenID» означает OpenID Connect 1.0; старый OpenID 2.0 — другой протокол.</p>
<div class="table-scroll"><table><thead><tr><th></th><th>OAuth 2.0</th><th>OpenID Connect</th></tr></thead><tbody><tr><td>Вопрос</td><td>Какой доступ разрешён?</td><td>Кто вошёл?</td></tr><tr><td>Результат</td><td>Access token</td><td>ID Token + access token в Code Flow</td></tr><tr><td>Получатель</td><td>API / Resource Server</td><td>ID Token предназначен клиенту / RP</td></tr><tr><td>Запрос</td><td>Например, scope=documents:read</td><td>Обязательно scope=openid</td></tr></tbody></table></div>
<p>${link(refs.oauth+'#section-1','RFC 6749')} · ${link(refs.core+'#Introduction','OIDC Core')}</p>
<h3>Кто есть кто</h3><p>Браузер — посредник пользователя. Client / RP — ваше приложение. Authorization Server / OP — провайдер авторизации и аутентификации. Resource Server — API. UserInfo находится у провайдера в классическом OIDC-примере. Отдельная станция Resource Server всегда представляет бизнес-API; при входе через UserInfo она не участвует. Возможность вызова других API определяется аудиторией и scopes access token.</p>
<details open><summary>Почему сначала code, а потом токены?</summary><p>Через адресную строку браузера передаётся одноразовый code. Сервер приложения обменивает его напрямую у провайдера, предъявляя verifier и свои credentials. В этой архитектуре ID Token, access token и client secret не попадают во frontend. Все сетевые переходы предполагают HTTPS.</p><p>${link(refs.oauth+'#section-4.1','Authorization Code Grant')}</p></details>
<details><summary>state, nonce, PKCE и client secret</summary><div class="table-scroll"><table><tr><th>Механизм</th><th>Что связывает</th><th>Где проверяется</th></tr><tr><td>state</td><td>Ответ с браузерной транзакцией</td><td>Callback клиента</td></tr><tr><td>nonce</td><td>ID Token с попыткой входа</td><td>Клиент после получения ID Token</td></tr><tr><td>PKCE S256</td><td>Code с обладателем verifier</td><td>Token endpoint</td></tr><tr><td>Client auth</td><td>Запрос с зарегистрированным клиентом</td><td>Token endpoint</td></tr></table></div><p>state рекомендуется OAuth Core; nonce опционален в OIDC Code Flow, но обязателен к проверке, если отправлен. Здесь оба включены. RFC 9700 требует PKCE для public clients и рекомендует его для confidential clients. Защита от CSRF обязательна; спецификация допускает разные комбинации механизмов при выполнении их условий.</p><p>${link(refs.pkce,'RFC 7636')} · ${link(refs.bcp+'#section-2.1','RFC 9700 §2.1')}</p></details>
<details><summary>Discovery и ключи подписи</summary><p>Настройте доверенный issuer. Его <code>/.well-known/openid-configuration</code> сообщает authorization endpoint, token endpoint, UserInfo и <code>jwks_uri</code>. Значение issuer должно точно совпадать с ожидаемым. JWKS содержит открытые ключи, не client secret. Выбор по <code>kid</code> ещё не проверка подписи; алгоритмы берутся из вашей политики и согласованной конфигурации, не только из токена.</p><p>Ключи ротируются: предусмотрите обновление кеша при неизвестном kid, ограничение частоты и отказ при недоступности доверенного ключа. Не скачивайте ключи с произвольного URL, взятого из недоверенного JWT.</p><p>${link(refs.discovery+'#ProviderConfig','OIDC Discovery')} · ${link(refs.core+'#RotateSigKeys','Ротация ключей')}</p></details>
<details><summary>Claims, scopes и пользователь</summary><p><code>scope</code> задаёт запрошенную область разрешения. <code>claim</code> — утверждение, например sub или name. Запрос profile не гарантирует присутствия каждого профильного поля. UserInfo необязателен, если нужные данные уже доступны. Email может меняться; ключ учётной записи — <code>(iss, sub)</code>. Pairwise sub может различаться у одного человека для разных клиентов.</p><p>${link(refs.core+'#Claims','OIDC Claims')} · ${link(refs.core+'#SubjectIDTypes','Subject Identifiers')}</p></details>
<details><summary>Что меняется для SPA и мобильного приложения?</summary><p>Браузерный frontend и обычное native-приложение — public clients: в них нельзя надёжно спрятать общий client secret. Их Code Flow использует PKCE. Показанный парк моделирует серверный web client, поэтому не переносите схему хранения токенов в SPA без отдельного решения об архитектуре.</p><p>В BFF-подходе сервер выступает OAuth-клиентом и хранит токены, а браузер работает через сессионную cookie. PKCE защищает обмен кода, но не устраняет XSS, утечки в логах или CSRF остальных запросов.</p><p>${link(refs.oauth+'#section-2.1','Типы клиентов')} · ${link(refs.bcp+'#section-2.1.1','Современная защита Code Flow')}</p></details>
<details><summary>Другие flows: что знать при миграции</summary><div class="table-scroll"><table><tr><th>Flow</th><th>Назначение и статус</th></tr><tr><td>Code + PKCE</td><td>Основной маршрут этого атласа для интерактивного входа и доступа.</td></tr><tr><td>Client credentials</td><td>Сервис от своего имени; без пользовательского входа и ID Token.</td></tr><tr><td>Implicit</td><td>Есть в классических спецификациях. Выдачу access token через authorization response RFC 9700 использовать не рекомендует.</td></tr><tr><td>Hybrid</td><td>OIDC сочетает code с ID Token и/или access token во front channel. Отдельные проверки nonce, c_hash и at_hash; не цель этой базовой миграции.</td></tr><tr><td>Password grant</td><td>RFC 9700 запрещает его использование. Не модернизируйте вход вокруг передачи пароля пользователя клиенту.</td></tr></table></div><p>Специализированные расширения: Device Authorization, PAR/JAR, DPoP и mTLS. Их применимость зависит от клиента и требований; они не являются обязательной частью всякого OIDC-входа.</p><p>${link(refs.bcp+'#section-2','Security BCP')} · ${link(refs.core+'#HybridFlowAuth','OIDC Hybrid Flow')}</p></details>
<details><summary>Выход, отзыв и истечение — разные события</summary><p>Удаление cookie завершает локальную сессию приложения. RP-Initiated Logout обращается к <code>end_session_endpoint</code> для выхода у OP; redirect после выхода должен быть заранее разрешён. Отзыв refresh/access token — отдельная операция. Ни локальный выход, ни истечение ID Token не означают мгновенного отзыва всех access tokens.</p><p>Для JWT access tokens с локальной проверкой API может узнавать об отзыве только по предусмотренному механизму или после истечения. Для introspection API проверяет состояние у сервера авторизации; учтите кеширование ответа.</p><p>${link(refs.logout,'RP-Initiated Logout')} · ${link(refs.revoke,'Token Revocation')} · ${link(refs.introspection,'Token Introspection')}</p></details>
<div class="dialog-callout"><p>Это модель протокольного обмена, а не OAuth-сервер. Длительность шагов условна. Криптография, пароли и HTTP-запросы здесь не выполняются; секреты и токены демонстрационные. Сценарий показывает, где проверки должны происходить.</p></div>`;
export const audits=[
['Определить роль вашей реализации','RP/client, OP/authorization server или resource server? От роли зависит набор требований.'],
['Зафиксировать поддерживаемый профиль','Типы клиентов, response_type, grant types, scopes, алгоритмы, методы client auth; разделить MUST, SHOULD и локальную политику.'],
['Проверить регистрацию и redirect_uri','Точное совпадение разрешённых URI по применимому профилю; отсутствие open redirect и client secret во frontend.'],
['Привязать попытку к браузеру','Случайный одноразовый state и привязка транзакции к сессии. Проверять и очищать на callback.'],
['Включить PKCE S256','Новый verifier на транзакцию; проверить challenge, отсутствие downgrade и обмен неправильного verifier.'],
['Проверять code и клиента','Короткий срок, одноразовость, привязка к client_id и redirect_uri; client authentication для confidential clients.'],
['Проверять ID Token','Доверенный issuer, алгоритм и подпись, aud/azp, exp, политика iat, отправленный nonce; auth_time при запросе max_age.'],
['Корректно определять пользователя','Ключ (iss, sub); совпадение sub UserInfo и ID Token. Не считать email устойчивым идентификатором.'],
['Разделить типы токенов','API не принимает ID Token; access token проверяется по своему профилю, ресурсу, сроку и scope.'],
['Продумать refresh и отзыв','Ротация/привязка, конкурентные refresh-запросы, reuse detection, сроки и поведение после отзыва.'],
['Разделить три состояния','Сессия приложения, SSO у OP и действительность токенов. Проверить logout и повторный вход.'],
['Проверить доверие к конфигурации','Issuer, discovery, JWKS rotation, allowlist алгоритмов, кеш, неизвестный kid, недоступность провайдера.'],
['Проверить отрицательные сценарии','Подмена state/nonce, replay code, неверная aud, истечение, consent denied, redirect mismatch, утечки токенов в URL и логах.'],
['Пройти применимые conformance-тесты','Ролевой набор OIDF и интеграционные тесты с другим провайдером/клиентом; не объявлять соответствие по happy path.']];
export const sourcesHTML=`<h2>Карта первоисточников</h2><p>Классический протокол и современная безопасность читаются вместе. Ссылки проверены 15 сентября 2026 года. Маршруты проекта основаны на предоставленных UML «Pasted text.txt»; полный shared-разговор недоступен.</p><ul><li>${link(refs.core,'OpenID Connect Core 1.0, errata set 2')} — ID Token, claims, Code/Implicit/Hybrid flows, UserInfo.</li><li>${link(refs.oauth,'RFC 6749')} — OAuth 2.0, роли, grants, endpoints, ошибки.</li><li>${link(refs.pkce,'RFC 7636')} — PKCE и S256.</li><li>${link(refs.bcp,'RFC 9700, январь 2025')} — актуальный Security Best Current Practice, обновляющий прежние рекомендации.</li><li>${link(refs.discovery,'OpenID Connect Discovery 1.0')} — metadata, issuer, JWKS.</li><li>${link(refs.bearer,'RFC 6750')} — Bearer token и ошибки API.</li><li>${link(refs.jwt,'RFC 9068')} — профиль JWT access tokens; не любой access token обязан быть JWT.</li><li>${link(refs.introspection,'RFC 7662')} — проверка состояния токена.</li><li>${link(refs.revoke,'RFC 7009')} — отзыв токенов.</li><li>${link("https://www.rfc-editor.org/rfc/rfc9470.html","RFC 9470")} — step-up challenge и контекст аутентификации.</li><li>${link(refs.logout,'RP-Initiated Logout 1.0')} — выход у OP.</li></ul><p>Авторская визуальная модель вдохновлена ${link('https://laurentiugabriel.github.io/rocket-engine/','Rocket Engine Works')}. Примеры и геометрия парка созданы для этого атласа.</p>`;

Object.assign(stations,{gateway:{name:'Калитка(-и)',role:'Gateway / proxy',color:'#e5c77a',x:-3.8,z:.6,h:2.2}});
export function stationFor(id,kind){const base=stations[id];if(!base)return null;if(isProject(kind)){const m={client:{name:'authorization',role:'OIDC Client / RP'},provider:{name:'auth ID',role:'OpenID Provider / AS'},api:{name:'Сервис экосистемы',role:'Бизнес-API · в UML без вызовов'}};return {...base,...(m[id]??{})};}return {...base,...(id==='provider'?{role:'OP / AS · включает UserInfo'}:{})};}
